### ISSUE TITLE
After add Russian locales menu item DISAPPEARED!

### ISSUE THREAD

**Issue by led9** [constructor-s/close-other-tabs#3]
Hello!
Thank you for adding RU Locales!
In english your extension work normally (before update)
Now it has been updated and the menu item is gone!
There is none, at all.

The extension can be installed / removed without any problems, the description of the extension is also normal, but it is not visible in the menu.
See what the matter is, please.

**Comment by led9** [comment]
I use Russian localization, maybe the menu item has not disappeared in English.
But in Russian there is no menu item "Закрыть другие вкладки" at all. ("Close other tabs" in russian)

**Comment by xtemp09** [comment]
The same issue.

FF 79.0 x64, Windows 7

[FF version.txt](https://github.com/constructor-s/close-other-tabs/files/5243883/FF.version.txt)

**Comment by valerafcc** [comment]
When using the English language in the browser settings, the item "close other tabs" is present in the context menu.
When using the Russian language in the browser settings, the item "close other tabs" is missing in the context menu.
Please check

**Comment by constructor-s** [comment]
Thank you all for your wonderful contribution. It should be fixed in the latest version 1.0.4: https://addons.mozilla.org/en-US/firefox/addon/close-other-tabs-menu/versions/

Reference commit: https://github.com/constructor-s/close-other-tabs/commit/f54e7f490540dd81b68ec84f9f1755e29a2bb61a - this is an (over-engineered) issue when forking from the original repo.
